@startuml
:patient: -> (Patient)
(RelatedPerson) <- :guardian:


(Consent) -> (Patient) : Consent.patient
(Consent) -> (RelatedPerson) : Consent.agent.reference
(Patient) <- (RelatedPerson) : RelatedPerson.patient
(RelatedPerson) --* (Consent) : **extension**
@enduml